# Generated by Django 4.2.4 on 2023-12-21 09:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=20)),
                ('address', models.CharField(default=None, max_length=50)),
                ('phone', models.CharField(default=None, max_length=50)),
                ('mail', models.CharField(default=None, max_length=50)),
                ('vat', models.CharField(default=None, max_length=20)),
                ('bankAccountNr', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('address', models.CharField(default=None, max_length=50)),
                ('phone', models.CharField(default=None, max_length=50)),
                ('mail', models.CharField(default=None, max_length=50)),
                ('vat', models.CharField(default=None, max_length=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.account')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceDate', models.DateTimeField(auto_now_add=True)),
                ('dueDate', models.DateTimeField(default=datetime.datetime(2024, 1, 4, 11, 53, 45, 368213))),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.account')),
                ('customerAccount', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.customeraccount')),
            ],
        ),
        migrations.CreateModel(
            name='Vat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='M24', max_length=50)),
                ('description', models.CharField(default='VAT (Value Added Tax @ 24%)', max_length=50)),
                ('percent', models.DecimalField(decimal_places=2, default='24%', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceRows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('quantity', models.IntegerField(default=None)),
                ('total', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.invoice')),
                ('vat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.vat')),
            ],
        ),
    ]
