# Generated by Django 4.2.4 on 2023-12-29 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='dueDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 12, 11, 12, 37, 96752)),
        ),
        migrations.AlterField(
            model_name='invoicerows',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
