# Generated by Django 4.2.4 on 2023-12-29 12:50

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_invoice_duedate_alter_vat_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='dueDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 12, 14, 50, 50, 990970)),
        ),
        migrations.AlterField(
            model_name='invoicerows',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoicerows',
            name='quantity',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
