# Generated by Django 4.2.4 on 2024-01-11 10:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_invoice_duedate_alter_invoicerows_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='dueDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 25, 12, 16, 18, 21144)),
        ),
        migrations.AlterField(
            model_name='invoicerows',
            name='vat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.vat'),
        ),
    ]
