# Generated by Django 4.2.4 on 2024-01-11 11:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_invoice_duedate_alter_invoicerows_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='dueDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 25, 13, 25, 2, 404097)),
        ),
        migrations.AlterField(
            model_name='invoicerows',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.invoice'),
        ),
    ]
