# Generated by Django 4.2.4 on 2024-02-05 09:27

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_invoicerows_total_with_tax_alter_invoice_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicerows',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='dueDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 11, 27, 51, 708780)),
        ),
    ]
